//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominus.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Relatorio
    {
        public System.Guid IdRelatorio { get; set; }
        public System.Guid IdTipoRelatorio { get; set; }
        public System.Guid IdUsuario { get; set; }
        public string Nome { get; set; }
        public string InfoLinha { get; set; }
        public string InfoColuna { get; set; }
    
        public virtual TipoRelatorio TipoRelatorio { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
