//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominus.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelatorioTransacoes
    {
        public System.Guid IdTransacao { get; set; }
        public System.Guid IdUsuario { get; set; }
        public string Tipo { get; set; }
        public string Modo { get; set; }
        public string Categoria { get; set; }
        public string Descrição { get; set; }
        public System.DateTime Data { get; set; }
        public decimal Valor { get; set; }
        public string Comentário { get; set; }
    }
}
