//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominus.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transacao
    {
        public int IdTransacao { get; set; }
        public int IdUsuario { get; set; }
        public Nullable<int> IdCategoria { get; set; }
        public string Identificacao { get; set; }
        public string Descricao { get; set; }
        public decimal Valor { get; set; }
        public System.DateTime Data { get; set; }
        public System.TimeSpan Hora { get; set; }
        public string Comentario { get; set; }
        public int RepetirMes { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
