//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominus.DataModel
{
    using Newtonsoft.Json;
    using System;

    public partial class Transacao
    {
        public Guid IdTransacao { get; set; }
        public Guid IdUsuario { get; set; }
        public Guid IdCategoria { get; set; }
        public string Identificacao { get; set; }
        public string Descricao { get; set; }
        public string TipoFluxo { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public Nullable<DateTime> Data { get; set; }
        public string Comentario { get; set; }
        public int Provisionado { get; set; }
        public Nullable<decimal> ValorProvisao { get; set; }
        public Nullable<DateTime> DataProvisao { get; set; }

        [JsonIgnore]
        public virtual Categoria Categoria { get; set; }
        [JsonIgnore]
        public virtual Usuario Usuario { get; set; }
    }
}
